[package]
name = "aes-modes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.1"
<<<<<<< Updated upstream
array-init = "2.1.0"
rand = "0.8.5"
=======
rayon = "1.10.0"
>>>>>>> Stashed changes
